name: Haskell CI

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        ghc: ["8.10.7"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        cabal: ["3.6.2.0"]

    steps:

    - name: Environment
      run: env

    - name: Install Haskell tooling
      run: |
        ghcup install ghc   ${{ matrix.ghc   }}
        ghcup set     ghc   ${{ matrix.ghc   }}
        ghcup install cabal ${{ matrix.cabal }}
        ghcup set     cabal ${{ matrix.cabal }}
        echo "CABAL_DIR=$HOME/.cabal" >> $GITHUB_ENV
        echo "TEMP=$HOME/.tmp" >> $GITHUB_ENV

    - name: Set cache version
      run: echo "CACHE_VERSION=grFfw8r" >> $GITHUB_ENV

    - uses: actions/checkout@v2

    - name: Cabal update
      run: cabal update -v3
